In [1]:
import torch

In [2]:
t1 = torch.tensor(4.0)

In [3]:
t1.dtype

torch.float32

In [4]:
t2 = torch.tensor([1.,2,3,4,5])

In [5]:
t3 = torch.tensor([[5.,6], [7,8], [9,10]])

In [9]:
print(t3)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [10]:
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])

In [13]:
print(t4)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


In [14]:
t1.shape

torch.Size([])

In [19]:
t2.shape

torch.Size([5])

In [17]:
t3.shape

torch.Size([3, 2])

In [20]:
t4.shape

torch.Size([2, 2, 3])

In [21]:
t4.shape

torch.Size([2, 2, 3])

In [34]:
x = torch.tensor(3.) #not interested in this derivative 
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [35]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [36]:
y.backward()

In [37]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [42]:
t6 = torch.full((3, 2), 42)

In [44]:
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [45]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8


tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [46]:
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])